### PR TITLE
Data::Dumper and debugging code (was: Misc fixes)

### PR DESCRIPTION
**Pull request by jvolkening**
There is a test specifically to check for `Data::Dumper` being loaded, so these need to be removed. Possibly better just to remove the lines altogether.

### CODE REVIEW

**Comment by vincentl** [comment]
I favor removing code rather than commenting (unless the comment documents why the active code is doing something unexpected or non-standard).

**Comment by jvolkening** [comment]
Along with the changes here, some other modules also have Data::Dumper code interspersed and commented out, sometimes along with other debugging code. Several modules make use of a hard-coded "DEBUG' constant. What about using something like `Smart::Comments` to replace these? This would clean things up a bit at the cost of an additional dependency.

**Comment by vincentl** [comment]
Smart::Comments looks good to me.

**Comment by vincentl** [comment]
Before merging the PR, I modified it to also use "constant folding" to conditionally turn on Smart::Comments.  I added a description to Documentation/Hackers-Guide as well.  Let me know if you see any issues with what I wrote in the Hackers-Guide (or the strategy in general).  Thanks!

**Pull request merged**
