### PR TITLE
Fixed XETRA, Tradegate and SInvestor after webpage was restructured

### LINKED ISSUE #350: `XETRA.pm` no longer working
I'm using v1.54 and believe sometime this week using `xetra` as source stopped working. I'm getting an error
```sh
 Can't call method "look_down" on an undefined value at /usr/share/perl5/Finance/Quote/XETRA.pm line 66
```
I don't speak Perl, but my best guess is that the used website changed a class name (though I've never been to the website before or was even aware which site it's using).

Replacing
```perl
   my $lastvalue = $tree->look_down('class'=>'si_inner_content_box');
```
with
```perl
   my $lastvalue = $tree->look_down('class'=>'contentwrapper');
```
seems to fix the issue and I can obtain rates again.

### PR DESCRIPTION
**Pull request by mumpitzstuff**
Fixes #350.

### CODE REVIEW

**Comment by bpschuck** [comment]
Awesome! Thanks for the quick response. BTW - Prefer most recent changes at the top of the list in `Changes` file.

**Comment by mumpitzstuff** [comment]
changes reordered...

**Comment by mumpitzstuff** [comment]
@bpschuck Is something missing?

**Comment by bpschuck** [comment]
> @bpschuck Is something missing?

No sir. I've just been extremely busy at the day job and personal life. Besides holiday related goodies, getting my late father's house prepped for sale (including repairing hurricane damage).

**Comment by mumpitzstuff** [comment]
Oh sry then please excuse my impatience.

**Comment by bpschuck** [comment]
@mumpitzstuff - Before merging the pull request I executed the test suites for the 3 modules. t/extra.t and t/tradegate.t failed with errors. t/sinvestor.t successfully completed all 94 planned tests. I did not investigate further, but usually failures occur due to symbols no longer being valid. If you could please review and fix the test suites that would be greatly appreciated.
Thank you once again for contributing.

**Comment by mumpitzstuff** [comment]
The bond used for the tradegate and xetra tests was not valid anymore. Therefore i had to use another one (tests fixed). But now an error occured because bonds seems to have a different output. Therefore i adjusted sinvestor, xetra and tradegate another time to fix this issue hopefully.

**Comment by bpschuck** [comment]
PR merged. Thank you.

**Pull request merged**
