### PR TITLE
Minor documentation cleanup (Add install section to 'Documentation/RE…

### PR DESCRIPTION
**Pull request by Jujhar**
…ADME' + Remove Documentation/Readme.txt + Add finance-quote-user to 'htdocs/discussion')

Touch ups for #316

### CODE REVIEW

**Comment by bpschuck** [comment]
@Jujhar

Thanks. I created the issue as more of a reminder to myself for the next time I'm working on another issue or while doing some housekeeping just before pushing a release to CPAN. I just didn't care to create a PR for just these changes. But, since it's done, less for me to do. Thanks.

**Comment by Jujhar** [comment]
ok

**Comment by bpschuck** [comment]
I'm not annoyed or anything, just surprised that someone not part of the F::Q team submitted a PR for it not even 24 hours after I created the issue. It's usually team members creating PRs for issues submitted by random F::Q users.

**Comment by Jujhar** [comment]
Yes, you are correct.
I'm geared towards larger organizations where they assume random people will contribute.
All new work does give you some experience!

**Pull request merged**
