### PR TITLE
New module MumbaiStock.pm

### PR DESCRIPTION
**Pull request by bgr22112**
# MumbaiStock Pull Request Documentation  

## NAME  
MumbaiStock.pm is a Perl module to fetch end of day stock quotes from the [BSE India](https://www.bseindia.com). MumbaiStock.pm integrates with Finance Quotes to enable stock quotes update from BSE India into Gnucash.

## WHY MUMBAISTOCK.PM  
Stock quotes (daily bhav copy) are published at end of each trading day by BSE India and are called the daily bhavcopy. These are in a ZIP file that contains a CSV format file with stock quotes for all stocks traded during the day.

BSE India recently modified the CSV file to conform to their new standardized format that they notified vide [this notification](https://www.bseindia.com/markets/MarketInfo/DispNewNoticesCirculars.aspx?page=20221201-52). That notification refers to this [annexure](https://www.bseindia.com/markets/MarketInfo/DownloadAttach.aspx?id=20221201-52&attachedId=528afdfb-749b-4636-80fb-7576b91f2f2c) that explains the specifications of the new file format.

MumbaiStock.pm module uses the new standardized format of the daily bhav copy to retrieve stock quotes.

## DEVELOPMENT TOOLS USED  
MumbaiStock.pm module is Perl code that aligns with [Finance::Quote hackers guide](https://github.com/finance-quote/finance-quote/blob/master/Documentation/Hackers-Guide). Code editor of choice was [Geany](https://www.geany.org/). [Visual Studio Code](https://code.visualstudio.com/) could have been used, but why use something much bigger in size :-).

The [finance-quote repository](https://github.com/finance-quote/finance-quote) was forked to https://github.com/bgr22112/finance-quote

### ADDED   
[MumbaiStock.pm](https://github.com/bgr22112/finance-quote/blob/master/lib/Finance/Quote/MumbaiStock.pm) - New perl module to retrieve stock quotes from bseindia standardized bhavcopy new format.
### MODIFIED   
[Quote.pm](https://github.com/bgr22112/finance-quote/blob/master/lib/Finance/Quote.pm) - Added MumbaiStock in the MODULES list in it's alphabetical order.
[Modules-README.yml](https://github.com/bgr22112/finance-quote/blob/master/Modules-README.yml) - Modified to add a section for mumbaistock with it's test cases file mumbaistock.t in it's alphabetical order.
[README.md](https://github.com/bgr22112/finance-quote/blob/master/README.md) -  A line of MumbaiStock added in alphabetical order to this file.
### TESTS   
[mumbaistock.t](https://github.com/bgr22112/finance-quote/blob/master/t/mumbaistock.t) - Added to create perform tests for mumbaistock, which were successfully completed.

## HOW IT'S BEEN DONE  
The standardised BSE daily bhav copy (price list) is published at end of trading day at https://www.bseindia.com/markets/MarketInfo/BhavCopy.aspx. The data is in the file named as EQDDMMYY_CSV.ZIP where DD = date, MM = month and YYYY = year. An example of which is https://www.bseindia.com/download/BhavCopy/Equity/BSE_EQ_BHAVCOPY_07072023.ZIP.

The above new standardized format file has been used in MumbaiStock.pm.

## CODE BREAKDOWN - MumbaiStock.pm  
Current date is needed to retrieve the bhav copy from the bseindia.com web site. Break down the current date and time into it's various components of the day, month and year.

Build a variable for the file name that will be retrieved as BSE_EQ_BHAVCOPY_%02d%02d%4d.ZIP and build the URL from where the file has to be retrieved.

Fetch the file and unzip it as BSE_EQ_BHAVCOPY.csv in the /tmp folder.

If the file is not found i.e. there was no trading on the date specified, rebuild the file name by decrementing the date by 1 and try to fetch it till a file is found. Note that if there are network issues, this can loop indefinitely. Therefore, decrementing is done only 5 times.

If the file has been successfully retrieved, then process the prices for each symbol found in the CSV file.

Lastly, in Quote.pm MumbaiStock has been added as a module in @MODULES in it's alphabetical sequence.

That's all.

## TEST CASES   
  testfile: mumbaistock.t
  testcases:
    - 532540
    - 500008
    - 500400
    - 500387
    - 500390
    - 500469

## COPYRIGHT & LICENCE  
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.

Currency and stock price information fetched through this module is bound by the terms and conditons of the data source.

Other copyrights and conditions may apply to data fetched through this module. Please refer to the sub-modules for further information.

## AUTHORS  
Rajan Vaswani (www.askmeaboutlinux.com)

### A BIG THANK YOU TO @bpschuck
for letting me know that the pull request needs to be documented properly.

### CODE REVIEW

**Comment by bpschuck** [comment]
Thanks again. 2 questions.

- Does this module provide something not in the existing BSEIndia.pm module that also uses data retrieved from bseindia.com? Different or additional funds and/or securities? 
- Assuming a directory like `/tmp` exists is bad practice. Code needs to work on Unix/Linux, Mac OSX, and MS Windows. The BSEIndia.pm module has logic for that. But truthfully, reading the downloaded file into a variable and parsing the data out of that would be a cleaner solution (and something I have been thinking of updating BSEIndia.pm with).

**Comment by bgr22112** [comment]
> Thanks again. 2 questions.
> 
>     * Does this module provide something not in the existing BSEIndia.pm module that also uses data retrieved from bseindia.com? Different or additional funds and/or securities?
> 
Bhav copies are available at https://www.bseindia.com/markets/MarketInfo/BhavCopy.aspx
BSEIndia.pm uses data file at https://www.bseindia.com/download/BhavCopy/Equity/EQ271023_CSV.ZIP which is the old format.
MumbaiStock.pm uses data file at https://www.bseindia.com/download/BhavCopy/Equity/BSE_EQ_BHAVCOPY_27102023.ZIP which is the new standardised format.

Both will work as of today till the old format is sunset.

>     * Assuming a directory like `/tmp` exists is bad practice. Code needs to work on Unix/Linux, Mac OSX, and MS Windows. The BSEIndia.pm module has logic for that. But truthfully, reading the downloaded file into a variable and parsing the data out of that would be a cleaner solution (and something I have been thinking of updating BSEIndia.pm with).
The variable that determines the temp folder is in line 57 in MumbaiStock.pm reproduced as below:
my $cachedir = $ENV{TMPDIR} // $ENV{TEMP} // '/tmp/';

Thank you for your feedback. As a newbie, I am learning a lot from you. Eternally grateful.

**Comment by bpschuck** [comment]
So while this uses different source data from bseindia.com, it provides no additional benefit over using BSEIndia.pm? If the data file downloaded by BSEIndia.pm is going to be deprecated (aka no longer available), wouldn't it make better sense for this new module be named BSEIndia.pm and completely replace the current module?

**Comment by bgr22112** [comment]
> module be named BSEIndia.pm and completely replace the current module

The old data source has not be deprecated by the BSE even though repeated deadlines to do so have lapsed. It could be a risk to replace BSEIndia.pm at this juncture with the new data source.

**Comment by bpschuck** [comment]
As the person who does all the housekeeping and prep work for each release pushed to CPAN, I see it as maintaining 2 modules that perform the same function. With no real benefit in what is basically duplicating an existing module, I am likely going to close this PR without merging it.

**Comment by bgr22112** [comment]
> As the person who does all the housekeeping and prep work for each release pushed to CPAN, I see it as maintaining 2 modules that perform the same function. With no real benefit in what is basically duplicating an existing module, I am likely going to close this PR without merging it.

Thanks for your feedback @bpschuck. It's fine. You can close the PR without merging it. As a newbie, I now understand it's a duplicate effort for a maintainer. I could rewrite BSEIndia.pm to use the new data source into a memory variable instead of downloading the file to a temp file? Would it be okay? In any case, the new data source works too.

**Pull request closed without merging**
