### PR TITLE
Re-enable morningstar.ch.

### PR DESCRIPTION
**Pull request by fritteli**
Please include morningstar.ch again - all that's needed is the HTTPS URLs instead of the HTTP URLs.

### CODE REVIEW

**Comment by bpschuck** [comment]
Thank you for your contribution. It would be a huge help to the maintainers if you could also update Modules-README.yml. Look at the entries for AlphaVantage.pm for an example of the information to be noted.
Thanks!

**Comment by fritteli** [comment]
Sure - thanks for the hint. I will update the file as soon as I have time, within the next few days, hopefully.

**Comment by fritteli** [comment]
I updated the Modules-README.yml

**Comment by bpschuck** [comment]
Thanks!

**Pull request merged**
