### PR TITLE
Fixes to TSP.pm

### PR DESCRIPTION
**Pull request by jhaiduce**
The U.S. Government Thrift Savings Plan (TSP) has retired its L2020 fund and added several new ones, breaking TSP.pm. This PR adds the new funds and removes the retired fund.

### CODE REVIEW

**Comment by bpschuck** [comment]
@jhaiduce, thank you for your contribution. However, please update Modules-README.yml and t/tsp.t. Mainly, the retired funds should not be tested for success or listed as test cases in Modules-README.yml.
Thank you.

**Comment by jhaiduce** [comment]
> @jhaiduce, thank you for your contribution. However, please update Modules-README.yml and t/tsp.t. Mainly, the retired funds should not be tested for success or listed as test cases in Modules-README.yml.

@bpschuck, I just pushed commits implementing your requested changes.

**Comment by jhaiduce** [comment]
By the way, this should fix #145 .

**Comment by vincentl** [comment]
TSP changed again.  See issue #148.  Merging this change because it addresses the retired and new funds.

**Pull request merged**
