### PR TITLE
[MorningstarJP] Use XML from apl.wealthadvisor.jp

### LINKED ISSUE #443: www.wealthadvisor.co.jp change
www.wealthadvisor.co.jp, which is used by `MorningstarJP.pm` (ref. #261) has changed.

It looks like the fund quote is available as non-public API in the form of `https://www.wealthadvisor.co.jp/xml/`__FUNDCODE__`.xml`, though it retrieves the whole history of quote values and becomes several hundreds kilo bytes size.

### PR DESCRIPTION
**Pull request by pkryger**
I took a liberty and rewritten the module to use XML and support new metadata. Unit tests I didn't change beside adding the fund names and updating line endings to unix style.

fixes #443

### CODE REVIEW

**Comment by bpschuck** [comment]
Thanks!
I took the liberty to modify the `Changes` file. I also see you used the new method/label/methodinfo declarations, very cool.
I'll do some of my own verifying and probably merge this before the end of the week.

**Comment by bpschuck** [comment]
The test file needs to be fixed.

```
bschuck@valhalla:~/tmp/finance-quote$ ONLINE_TEST=1 perl t/morningstarJP.t 
1..18
ok 1
Use of uninitialized value in substr at t/morningstarJP.t line 33.
Use of uninitialized value in substr at t/morningstarJP.t line 34.
substr outside of string at t/morningstarJP.t line 34.
Use of uninitialized value in substr at t/morningstarJP.t line 35.
substr outside of string at t/morningstarJP.t line 35.
Validation failed for type named DayOfMonth declared in package DateTime::Types (/usr/local/lib/x86_64-linux-gnu/perl/5.34.0/DateTime/Types.pm) at line 29 in sub named (eval) with value undef

Trace begun at Specio::Exception->new line 57
Specio::Exception::throw('Specio::Exception', 'message', 'Validation failed for type named DayOfMonth declared in package DateTime::Types (/usr/local/lib/x86_64-linux-gnu/perl/5.34.0/DateTime/Types.pm) at line 29 in sub named (eval) with value undef', 'type', 'Specio::Constraint::Simple=HASH(0x5b34ec276cd8)', 'value', undef) called at (eval 242) line 91
DateTime::_check_new_params('year', '', 'month', undef, 'day', undef) called at /usr/local/lib/x86_64-linux-gnu/perl/5.34.0/DateTime.pm line 177
DateTime::new('DateTime', 'year', '', 'month', undef, 'day', undef) called at t/morningstarJP.t line 37
# Looks like your test exited with 255 just after 1.
```

**Comment by bpschuck** [comment]
And this:

```
bschuck@valhalla:~/tmp/finance-quote$ ./Examples/stockdump.pl morningstarjp 2009100101
$VAR1 = {
          '2009100101success' => 0,
          '2009100101errormsg' => 'Search unavailable'
        };
```

Which is probably why the test is failing.

**Comment by bpschuck** [comment]
Disregard last comments. I forgot to switch to your `morningstarjp` branch before testing. I've gotten used to most people **not** creating branches in their forks when submitting PRs.

**Comment by bpschuck** [comment]
I'm also wondering if perhaps also presenting the method additionally as `wealthadvisorjp` may be a good idea? Since technically the Morningstar JP branding has been discontinued. Just thinking out loud.

```
sub methodinfo {
    return (
        morningstarjp => $METHODHASH,
        wealthadvisorjp => $METHODHASH,
    );
}
```

**Comment by pkryger** [comment]
> I'm also wondering if perhaps also presenting the method additionally as
> `wealthadvisorjp` may be a good idea? Since technically the Morningstar JP
> branding has been discontinued. Just thinking out loud.

> ```
>  sub methodinfo {
>     return (
>         morningstarjp => $METHODHASH,
>         wealthadvisorjp => $METHODHASH,
>     );
> }
> ```

I don't really know what's best approach here. But if `wealthadvisorjp` is
desireable, perhaps renaming the module to `WealthAdvisorJP.pm` and keeping the
`morningstarjp` as a backward compatibility source name? The downside,
especially from GnuCash perspective is that it will require update to contain
new strings. My understanding is, that GnuCash collects all possible source
names from the `Finance::Quote` and the opened `.book`, and then matches them
against the (currently) built in list.

Having said that, I don't have a particularly strong opinion on selecting best
method to proceed. Let me know what you decide, and should I make updates, or if
you prefer to do it yourself.

Cheers,

PK

**Comment by bpschuck** [comment]
> I don't really know what's best approach here. But if `wealthadvisorjp` is desireable, perhaps renaming the module to `WealthAdvisorJP.pm` and keeping the `morningstarjp` as a backward compatibility source name? The downside, especially from GnuCash perspective is that it will require update to contain new strings. My understanding is, that GnuCash collects all possible source names from the `Finance::Quote` and the opened `.book`, and then matches them against the (currently) built in list.

Keeping the GnuCash code and docs is a different issue. There has been some work lately in attempting to make it current. But in reality, that is a Sisyphean task as many of the sources are subject to constant change, or disappear altogether.

**Comment by bpschuck** [comment]
Hello @pkryger ,
Seems that `XML::LibXML` pulls in `Data::Dumper`. Which when running `TEST_AUTHOR=1 dzil test` causes the `t/05-data-dumper.t` test to fail. If you could look at other modules that can parse the XML, that would be appreciated. 
I'm cleaning up other issues flagged by running the tests.
Thanks.

**Pull request merged**
