### PR TITLE
Add get_features as FQ class method to advertise list of methods, modules, and module parameters

### PR DESCRIPTION
**Pull request by vincentl**
This is an experiment to implement the functionality discussed in #255.

There is one new function in Quote.pm at https://github.com/finance-quote/finance-quote/blob/440d4565e8bd2989afa9676709e57685fec9a582/lib/Finance/Quote.pm#L335 and modules with API keys have one new function, such as https://github.com/finance-quote/finance-quote/blob/440d4565e8bd2989afa9676709e57685fec9a582/lib/Finance/Quote/IEXCloud.pm#L40

The function is documented at https://github.com/finance-quote/finance-quote/blob/440d4565e8bd2989afa9676709e57685fec9a582/lib/Finance/Quote.pm#L1345 and truncated output looks like

```perl
{
  currency_modules => {
                        AlphaVantage => [
                                          'API_KEY'
                                        ],
                        ECB => [],
                        Fixer => [
                                   'API_KEY'
                                 ],
                        OpenExchange => [
                                          'API_KEY'
                                        ]
                      },
  quote_methods => {
                     aex => [
                              'AEX'
                            ],
                     alphavantage => [
                                       'AlphaVantage'
                                     ],
                     ...,
                     europe => [
                                 'ASEGR',
                                 'Bourso',
                                 'Sinvestor',
                                 'Tradegate',
                                 'Tradeville',
                                 'XETRA'
                               ],
                     ...
                   },
  quote_modules => {
                     AEX => [],
                     ASEGR => [],
                     ASX => [],
                     AlphaVantage => [
                                       'API_KEY'
                                     ],
                     BSEIndia => [],
                     ...,
                     ZA => []
                   }
}
```

### CODE REVIEW

**Comment by vincentl** [comment]
@bpschuck - wanted to bring your attention to an open [PR](https://github.com/Gnucash/gnucash/pull/1626) that will use this feature.  Depending on how the conversation proceeds with GnuCash developers, we may want to merge this into a release.

**Comment by bpschuck** [comment]
In the PR, please add a section to the Hackers-Guide documenting that modules with sources requiring an API key require the `parameters` method and what it should look like.

**Comment by bpschuck** [comment]
I also would like to personally test the changes being made/proposed to GnuCash along with the changes to F::Q before an official merge.
Thanks.

**Comment by bpschuck** [comment]
And Load::Module *was* needed in dist.ini. There was an issue reported a couple months back that was solved by making sure Load::Module was a certain version or later.

**Comment by vincentl** [comment]
@bpschuck - Thanks for adding the Hackers Guide section already!  

For the Load::Module, I'm not sure exactly what is going on.  At the very bottom of [this page](https://wiki.gnucash.org/wiki/MacOS/Quartz#Example:_Setting_up_a_Development_Environment)  I wrote instructions on how to install Finance::Quote for a new development environment a few months ago. When I tried to repeat the process myself a few days ago, it failed on Load::Module.  When I removed it, the install finished.  Further, when I search CPAN for Load::Module, "Module::Load" shows up but not Load::Module.  

Do you recall the details of why it was added?

**Comment by bpschuck** [comment]
I had a typo and had the name reversed, Module::Load is needed and it 
needs to be a somewhat recent version.

See the gnucash-user thread that starts here -> 
https://lists.gnucash.org/pipermail/gnucash-user/2023-March/105902.html

In short, I created a High Sierra VirtualBox VM. Once I installed the 
XCode bits, I installed Finance::Quote using cpan. I also could not 
fetch the quotes the user listed an examples. I forgot what the version 
of Load::Module was, I think it was .24 or .22. But it was in the 
low/mid .20s. I updated Module::Load to the current .36 and the issue 
was corrected.

Follow the thread for more info. But the dist.ini needs to specify a 
minimum version of Module::Load.

I have found that it is best to test on virgin OS's that do not have 
many other modules already installed and/or updated. At least as a full 
final test before pushing to CPAN.

**Comment by vincentl** [comment]
@bpschuck - thanks for the explanation.  Let me know if anything else needs polished on this branch before merge.

**Comment by bpschuck** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Its not going to be in v1.55 which I hope to push to CPAN this weekend. There has been a bunch of little changes and I dont care to add more possible culprits if issues arise. As I said a few responses ago, I would like to be able to test a version of GnuCash modified to utilize this PR.
Thanks.
-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - http://gpgtools.org

iHkEARECADkWIQRzL0H5rBaeDPnpeL1IjAeprJFQBwUCZFlVQhscYnNjaHVja0Bh
c2dhcmQtc3lzdGVtcy5jb20ACgkQSIwHqayRUAenpACgjT5OutKOvcld9Wk3DSDK
+OxspzcAn0upQBs//na7GZsp/BQJyBdwFzCj
=/ar0
-----END PGP SIGNATURE-----

**Comment by bpschuck** [comment]
This will likely be included in v1.56.

**Review by bpschuck — APPROVED** [review]
Changes reviewed. Looks okay.

**Pull request merged**
