### PR TITLE
India stocks: quotes from NSE and BSE

### LINKED ISSUE #142: Is there a module to load Indian stocks prices from NSE and BSE
Hi,
is there a .pm module in Finance::Quote which can give indian stocks related data?

### PR DESCRIPTION
**Pull request by shastry**
Adds methods:
nseindia, bseindia, india.

Fixes #142

### CODE REVIEW

**Comment by mark05e** [comment]
I was wondering if you could rename the modules to IndiaNSE and IndiaBSE. It would help identify the files quickly while sorting. It would fit in with [IndiaMutual.pm](https://github.com/finance-quote/finance-quote/blob/master/lib/Finance/Quote/IndiaMutual.pm)

**Comment by shastry** [comment]
All the other modules are named after the exchange name / source website.
(Barring IndiaMutual - which probably should've been named AMFIIndia.)

It can be updated if the project maintainers have an issue with it.

**Comment by shastry** [comment]
Debt segment - never used it. Perhaps another time. Or, may be you can create your own module `BSEIndiaDebt.pm` or such based on the bse module?

**Comment by mark05e** [comment]
> All the other modules are named after the exchange name / source website.

I had another look at the [modules folder](https://github.com/shastry/finance-quote/tree/india-stocks/lib/Finance/Quote) and it seems to be true.

> Or, may be you can create your own module `BSEIndiaDebt.pm` or such based on the bse module

I do not have much experience with coding in general. Will try something if/when I get time.

**Comment by bpschuck** [comment]
@shastry - Thank you for your contribution. I will be reviewing your pull request sometime in the next week or so. In the meantime, it would be appreciated if you could please also update Modules-README.yml with the information for the new modules. See the file for examples of what the maintainers are looking for.
Once again, thank you.
- Bruce S.

**Comment by shastry** [comment]
@bpschuck Sorry for the delay. Modules-README.yml is now updated.

**Comment by vincentl** [comment]
Thanks!

**Pull request merged**
