### PR TITLE
Delete the TiaaCref module and make the Yahoo module get TIAA/CREF quote...

### PR DESCRIPTION
**Pull request by mta1309**
The TiaaCref module doesn't work since the web site it uses is no longer being updated, but Yahoo has learned how to get TIAA/CREF quotes.

These changes delete the TIAA/CREF module and change the Yahoo USA module to handle requests to that module.  Most symbols are the same on Yahoo, but a few are different.  The changes fix things so either the old TIAA/CREF symbol or the Yahoo symbol will work.  Strictly speaking this change isn't required since people can use the Yahoo module directly, but if you have things set up to use the old symbols it is convenient to be able to continue using them.  With this change I am able to continue getting quotes in GnuCash without changing anything there.

### CODE REVIEW

**Comment by mta1309** [comment]
I realized soon after I submitted the pull request that I should fix a few things to make the replacement more compatible with the old version in terms of what it returns.  I added two more commits that largely accomplish this as well as some other minor cleanup.

I also hooked up Travis CI to my repository and, as you can see, it's happy.  The tests succeed unless ONLINE_TESTS is set, which is known to not work.  For tiaacref, all but the bogus symbol test passed with this set.  I'm not sure why it failed, but when I try it on my machine it works ok.

**Comment by ecocode** [comment]
hi

I checked the current tiaacref module. This is what gets returned for the testfile:

CREFmony,25.5337,02/19/2015
CREFmony,25.5337,02/18/2015
CREFmony,25.5337,02/17/2015
CREFmony,25.5337,02/13/2015
TIAAreal,340.5257,02/19/2015
TIAAreal,341.1001,02/18/2015
TIAAreal,340.6799,02/17/2015
TIAAreal,340.1158,02/13/2015
TLSRX,10.96,02/19/2015
TLSRX,10.96,02/18/2015
TLSRX,10.94,02/17/2015
TLSRX,10.95,02/13/2015
TCMVX,24.37,02/19/2015
TCMVX,24.43,02/18/2015
TCMVX,24.34,02/17/2015
TCMVX,24.28,02/13/2015
TLGRX,14.33,02/19/2015
TLGRX,14.34,02/18/2015
TLGRX,14.31,02/17/2015
TLGRX,14.32,02/13/2015
CREFbond,114.2138,02/19/2015
CREFbond,114.3329,02/18/2015
CREFbond,114.0335,02/17/2015
CREFbond,114.4158,02/13/2015

To me the data seems to be updated...

Maybe things restarted ?

best

**Comment by mta1309** [comment]
--On February 20, 2015 at 2:12:41 AM -0800 Erik Colson 
<notifications@github.com> wrote:

> To me the data seems to be updated...
>
> Maybe things restarted ?

Yes, they must have fixed it.  That explains why people stopped 
complaining about this on the GnuCash lists.  I hadn't noticed since 
I've been using the Yahoo replacement.

I amended my pull request so that the old tiaacref module is still 
there and unchanged while the Yahoo version is available as a fallback. 
I also added a tiaacref_direct method that won't fallback to the Yahoo 
version.  I thought it might be worth while to keep the Yahoo version 
around for future reference.  If you are so inclined you could use this 
version, although I see that you've closed my pull request.

         Mike

**Comment by ecocode** [comment]
Hi Mike.

Thanks for your code !
I unified your branch commits into one sole commit and pushed it to a new branch yahoo_tiaacref.
I need to check tests etc.
Also I kinda not like to hardcoded duplicate definition of %tiaacref_ids in both USA.pm and Tiaacref.pm.

Needs some work and new tests too before pushing to master :)

I'll close this pull request now as the code is now part of a specific branch of finance-quote. Please clone from there if you create new commits / pull requests

Erik

**Pull request closed without merging**
