### PR TITLE
Update to module IndiaMutual.pm & BSEIndia.pm. Eliminate need for temporary folder. Use standardised data file in BSEIndia.pm.

### PR DESCRIPTION
**Pull request by bgr22112**
# IndiaMutual & BSEIndia Pull Request Documentation  

## NAME  
IndiaMutual.pm & BSEIndia.pm are existing Perl modules in Finance::Quotes
IndiaMutual.pm gets end of day NAVs (net asset values) from the [AMFI India](https://www.amfiindia.com/) web site
BSEIndia.pm gets daily bhav copy stock quotes from the [BSE India](https://www.bseindia.com) web site

## WHY THIS CHANGE 
Indian Mutual Funds NAVs were retrieved by mirroring the file NAVAll.txt from the URL https://www.amfiindia.com/spages/NAVAll.txt into a temporary folder. This change eliminates the need to use a temporary folder by loading the contents of NAVAll.txt into a memory variable instead of mirroring the file to temporary folder.

BSE India stock quotes were retrieved by mirroring the daily bhav copy file using the earlier data format from URL https://www.bseindia.com/download/BhavCopy/Equity/EQ_ISINCODE_{DDMMYY}.zip which now uses the standardised data format from URL https://www.bseindia.com/download/BhavCopy/Equity/BSE_EQ_BHAVCOPY_{DDMMYYYY}.ZIP. It also eliminates the need to use a temporary folder by loading contents from the file into a memory variable instead of mirroring the file to temporary folder.

## DEVELOPMENT TOOLS USED  
IndiaMutual.pm & BSEIndia.pm modules are Perl code that align with [Finance::Quote hackers guide](https://github.com/finance-quote/finance-quote/blob/master/Documentation/Hackers-Guide). Code editor of choice was Geany on Linux which is available at https://www.geany.org/. vscode can be used too, but why use something much more bigger in size :-).

The [finance-quote repository](https://github.com/finance-quote/finance-quote) was forked to https://github.com/bgr22112/finance-quote.

### ADDED   
None

### MODIFIED   
**IndiaMutual.pm** - Changes to use a memory variable in place of a file.
**BSEIndia.pm** - Changes to use a memory variable in place of a file. Also to retrieve stock quotes data from the standardised data file.
**Modules-README.yml** - Modified the date when the change was done to IndiaMutual.pm & BSEIndia.pm
**Changes** - Added the changes made to IndiaMutual.pm & BSEIndia.pm

### TESTS   
indiamutual.t - Existing test for IndiaMutual, which were successfully completed.
bseindia.t - Existing test for BSEIndia, which were successfully completed.

## CODE BREAKDOWN - IndiaMutual.pm 
Used the HTTP request get to fetch the contents of NAVAll.txt into a variable.

$req = HTTP::Request->new(GET => $url);	#done to avoid downloading file
$reply = $ua->request($req);

Then store the file in a variable and split into an array to use for the update.

## CODE BREAKDOWN - BSEIndia.pm 
Used the HTTP request get to fetch the contents from the standardised bhavcopy into a variable.
$req = HTTP::Request->new(GET => $url);	#done to avoid downloading file
$reply = $ua->request($req);

Then store the file in a variable and split into an array to use for the update.
Updated the column names to conform to the standardised data file format retrieved from the bseindia URL.

That's all.

## TEST CASES   
  testfile: indiamutual.t
  testfile: bseindia.t

## COPYRIGHT & LICENCE  
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.

Currency and stock price information fetched through this module is bound by the terms and conditons of the data source.

Other copyrights and conditions may apply to data fetched through this module. Please refer to the sub-modules for further information.

## AUTHORS  
Rajan Vaswani (www.askmeaboutlinux.com)

### CODE REVIEW

**Comment by bgr22112** [comment]
@bpschuck, this change to IndiaMutual.pm removes the need to use the temp folders on any operating system to download the NAV file from amfiindia. It grabs the contents of that NAV file into a variable and updates the prices of India mutual funds.

**Comment by bpschuck** [comment]
@bgr22112,
Thank you for the contribution. But, you did not update Modules-README.yml file to indicate BSEIndia.pm has been changed/updated.

In addition, I do prefer that updating the "Changes" file is also done. The preference is to add recent changes to the top of the list immediately below the `{{$NEXT}}` line.

As some other PRs have been merged recently, it's also a time save for the maintainers if the remote branch of a PR is rebased. This helps avoid having to resolve conflicts when merging pull requests.

Thank you.

**Comment by bgr22112** [comment]
@bpschuck thanks for your inputs and feedback. I synced the project once again and made the modifications as you suggested into your comment. Trust these modifications address your comment.

Thank you for your time and patience.

**Comment by bpschuck** [comment]
Thanks again. But for the future, rebasing your branch instead of merging is preferred. A nice description of the difference is at [merging-vs-rebasing](https://www.atlassian.com/git/tutorials/merging-vs-rebasing).

**Pull request merged**
