### PR TITLE
Added Yahoos cookies and crumb capabilities.

### PR DESCRIPTION
**Pull request by ka-patel**
Added routines to fetch Yahoos cookies and crumb in order to retrieve quotes.

### CODE REVIEW

**Comment by bpschuck** [comment]
Not needed. YahooJSON.pm currency rate module has been changed to use the v8 API.

**Comment by bpschuck** [comment]
You also need to use fresh clone/fetches/rebase of the code before making further changes. Otherwise recent changes can get undone if I'm not careful merging pull requests.

**Comment by ka-patel** [comment]
Agree. 

 

My workflow is to blow out the existing code base completely, fork it, clone down and then make any necessary changes for pull request.

**Comment by bpschuck** [comment]
> My workflow is to blow out the existing code base completely, fork it, clone down and then make any necessary changes for pull request.

As I said, this PR undoes recent changes.

Thanks though. Even though I quickly closed this. I have the logic save in a Gist for future reference. At some point I expect the v8 API will require cookies and/or crumbs.

On a related note, we appreciate if PRs also include the appropriate changes to the `Modules-README.yml` and `Changes` files. `Modules-README.yml` is mentioned in the "Hacker's Guide", I need to add a line item in that checklist for the `Changes` file.

Thank you.

**Comment by ka-patel** [comment]
Noted. 

 

I will keep this note stared in my email client and will keep these in mind when submitting future PR. 

 

Not only will V8 require cookie and crumb but I suspect https://query2.finance.yahoo.com/v1/test/getcrumb will become restricted or will go away a lot sooner. I will review to see if this can be done away with, which I believe can be.

 

Regardless at least there is working modal of cookie and crumb in F::Q at this point…

**Pull request closed without merging**
