### PR TITLE
Fix Fund Library

### LINKED ISSUE #114: Fund Library, CA scraper not working
Hello, 
Some time after May 16, 2019, the date of my last price update, the "Fund Library, CA" scraper in F::Q stopped working. I suspect fundlibrary.com has changed their website. Other quotes are still working as expected through Alpha Vantage. None of the other Canadian mutual fund scrapers (BMO Nesbitt Burns, Canada 
Mutual, Finance Canada, TD Waterhouse Funds) seem to be working either, even after searching the gnucash mail list archives for methods people have used in the past.

When trying to get my quotes, I see:
"Unable to retrieve quotes for these items:
FUND: xxxxx
FUND: yyyyy
FUND: zzzzz
Continue using only the good quotes?"

As expected, selecting "No" will cancel and selecting "Yes" will update the other stock prices.

If any logs will help, let me know and I will post them.

Thanks,
Doug

### PR DESCRIPTION
**Pull request by dataBaseError**
Fixes #114

### CODE REVIEW

**Comment by DoughMucker** [comment]
I see the build is failing. FYI, I manually copied the code to the finance quote module and it is working for me. Thanks!

**Comment by patherror** [comment]
> 
> 
> I see the build is failing. FYI, I manually copied the code to the finance quote module and it is working for me. Thanks!

Hi, what is the process you used to copy the code to your computer to make it work?

**Comment by DoughMucker** [comment]
> Hi, what is the process you used to copy the code to your computer to make it work?

Assuming you're using windows, copy/paste the [new code](https://github.com/finance-quote/finance-quote/blob/9871379b7fd4732afce4d5966cba10964ee1d05d/lib/Finance/Quote/Cdnfundlibrary.pm) to C:\strawberry\perl\site\lib\Finance\Quote\Cdnfundlibrary.pm (or wherever you installed perl.)
If Cdnfundlibrary.pm is read-only you'll have to disable that first. 
Restart GnuCash.

**Comment by dataBaseError** [comment]
@DoughMucker I appreciate the feedback. I'm not very familiar with Perl however the build failure appears to be an issue with the Travis CI setup:
https://travis-ci.org/finance-quote/finance-quote/jobs/579933780#L941
```
$ dzil test --all
The program 'dzil' is currently not installed. To run 'dzil' please ask your administrator to install the package 'libdist-zilla-perl'
```

**Comment by patherror** [comment]
> 
> 
> > Hi, what is the process you used to copy the code to your computer to make it work?
> 
> Assuming you're using windows, copy/paste the [new code](https://github.com/finance-quote/finance-quote/blob/9871379b7fd4732afce4d5966cba10964ee1d05d/lib/Finance/Quote/Cdnfundlibrary.pm) to C:\strawberry\perl\site\lib\Finance\Quote\Cdnfundlibrary.pm (or wherever you installed perl.)
> If Cdnfundlibrary.pm is read-only you'll have to disable that first.
> Restart GnuCash.

Okay, I did that and the when I run price update, it doesn't fail.  But what 

> 
> 
> > Hi, what is the process you used to copy the code to your computer to make it work?
> 
> Assuming you're using windows, copy/paste the [new code](https://github.com/finance-quote/finance-quote/blob/9871379b7fd4732afce4d5966cba10964ee1d05d/lib/Finance/Quote/Cdnfundlibrary.pm) to C:\strawberry\perl\site\lib\Finance\Quote\Cdnfundlibrary.pm (or wherever you installed perl.)
> If Cdnfundlibrary.pm is read-only you'll have to disable that first.
> Restart GnuCash.

That seemed to work, and I got quotes, but I noticed the latest quotes I got were from July 31, 2019.  Do you get up to date quotes?

**Comment by DoughMucker** [comment]
> $ dzil test --all
> The program 'dzil' is currently not installed. To run 'dzil' please ask your administrator to install the package 'libdist-zilla-perl'

I'm of no help to you. Your commit is far beyond what I know and so is the error.

**Comment by DoughMucker** [comment]
> > > Hi, what is the process you used to copy the code to your computer to make it work?
> > 
> > 
> > Assuming you're using windows, copy/paste the [new code](https://github.com/finance-quote/finance-quote/blob/9871379b7fd4732afce4d5966cba10964ee1d05d/lib/Finance/Quote/Cdnfundlibrary.pm) to C:\strawberry\perl\site\lib\Finance\Quote\Cdnfundlibrary.pm (or wherever you installed perl.)
> > If Cdnfundlibrary.pm is read-only you'll have to disable that first.
> > Restart GnuCash.
> 
> Okay, I did that and the when I run price update, it doesn't fail. But what
> 
> > > Hi, what is the process you used to copy the code to your computer to make it work?
> > 
> > 
> > Assuming you're using windows, copy/paste the [new code](https://github.com/finance-quote/finance-quote/blob/9871379b7fd4732afce4d5966cba10964ee1d05d/lib/Finance/Quote/Cdnfundlibrary.pm) to C:\strawberry\perl\site\lib\Finance\Quote\Cdnfundlibrary.pm (or wherever you installed perl.)
> > If Cdnfundlibrary.pm is read-only you'll have to disable that first.
> > Restart GnuCash.
> 
> That seemed to work, and I got quotes, but I noticed the latest quotes I got were from July 31, 2019. Do you get up to date quotes?

I hadn't noticed that. But it is happening to me too!

**Comment by dataBaseError** [comment]
I've switched the date used from the response:

```
{
  "PriceAsOfDate": "/Date(1567641600000)/",
  "PriceAsOfDateString": "2019-09-05T00:00",
  "PerformanceAsOfDate": "/Date(1564531200000)/",
  "PerformanceAsOfDateString": "2019-07-31T00:00",
...
}
```

Instead of using `PerformanceAsOfDateString`, it will now use `PriceAsOfDateString`.

**Comment by dataBaseError** [comment]
> > $ dzil test --all
> > The program 'dzil' is currently not installed. To run 'dzil' please ask your administrator to install the package 'libdist-zilla-perl'
> 
> I'm of no help to you. Your commit is far beyond what I know and so is the error.

No problem.

**Comment by patherror** [comment]
> 
> 
> > > > Hi, what is the process you used to copy the code to your computer to make it work?
> > > 
> > > 
> > > Assuming you're using windows, copy/paste the [new code](https://github.com/finance-quote/finance-quote/blob/9871379b7fd4732afce4d5966cba10964ee1d05d/lib/Finance/Quote/Cdnfundlibrary.pm) to C:\strawberry\perl\site\lib\Finance\Quote\Cdnfundlibrary.pm (or wherever you installed perl.)
> > > If Cdnfundlibrary.pm is read-only you'll have to disable that first.
> > > Restart GnuCash.
> > 
> > 
> > Okay, I did that and the when I run price update, it doesn't fail. But what
> > > > Hi, what is the process you used to copy the code to your computer to make it work?
> > > 
> > > 
> > > Assuming you're using windows, copy/paste the [new code](https://github.com/finance-quote/finance-quote/blob/9871379b7fd4732afce4d5966cba10964ee1d05d/lib/Finance/Quote/Cdnfundlibrary.pm) to C:\strawberry\perl\site\lib\Finance\Quote\Cdnfundlibrary.pm (or wherever you installed perl.)
> > > If Cdnfundlibrary.pm is read-only you'll have to disable that first.
> > > Restart GnuCash.
> > 
> > 
> > That seemed to work, and I got quotes, but I noticed the latest quotes I got were from July 31, 2019. Do you get up to date quotes?
> 
> I hadn't noticed that. But it is happening to me too!

The code was updated by dataBaseError to include the correct variable name to get the latest price update, not the "latest performance date" price.

I think it looks all good now.

Thanks.

**Comment by DoughMucker** [comment]
I'm getting crashes while trying to get quotes now. GC is just crashing without any error shown. When I revert to the old Cdnfundlibrary.pm the crashes stop (but I don't get the mutual fund updates). Is there a way to get a log from F::Q or GC with details of what's happening?

**Comment by goodvibes2** [comment]
DoughMucker,
See https://wiki.gnucash.org/wiki/FAQ#Q:_Something_bad_happened.3B_how_can_I_help_debug.3F for info on GnuCash logs and Trace file.
Search https://wiki.gnucash.org/wiki/FAQ for gnu-fq-dump and gnu-fq-helper for easy way to check what FQ is returning.
There is no FQ logging but you can run perl with -d switch to debug a perl program if you are a programmer.

**Comment by goodvibes2** [comment]
Sorry, should be gnc-fq-dump and gnc-fq-helper. @&$# autocorrect...

**Comment by DoughMucker** [comment]
So there is a problem, but, I'm not proficient enough to fix it. Other fund quotes work, but this one fails where it worked once before:
perl "C:\Program Files (x86)\gnucash\bin\gnc-fq-dump" -v fundlibrary TDB3090
Error parsing time at C:/Strawberry/perl/lib/Time/Piece.pm line 597.

So the issue is essentially an invalid/unknown symbol causing a crash. Turning off quote retrieval for that quote allows for the correct retrieval of all the other quotes.

**Comment by bpschuck** [comment]
@dataBaseError Thank you for supplying fixes to the module. In addition to fixing the module, the maintainers also prefer that the test file be updated to include symbols that demonstrate the fix addresses the concerns in the related issue. If you can do that I can merge this pull request. But I'm not sure when @ecocode will be posting a new version to CPAN.
Thanks again.

**Comment by bpschuck** [comment]
@dataBaseError - I'd do it myself, but don't want to step on toes. If you could change the test symbols in t/cdnfundlibrary.t to NBC887 and TDB3533, I can merge your fix into the F::Q master.
You will also note I fixed the Travis CI build, needed to update the Perl versions.

**Comment by dataBaseError** [comment]
@bpschuck I really appreciate your help.

**Pull request merged**
