### PR TITLE
TSP - update URL, update handling of dates

### PR DESCRIPTION
**Pull request by vincentl**
Site seems to have stabilized and this pull request reflects that latest working version.

### CODE REVIEW

**Comment by bpschuck** [comment]
Thank you sir. 
I'm busy with other tasks for the next couple days, but I'll take a look when I can and either give you the thumbs up to merge or I'll do it myself.

**Comment by bpschuck** [comment]
Looks good Vincent. Before you merge, please add another bullet point to the Changes file.
Thanks!

**Review by bpschuck — CHANGES_REQUESTED** [review]
Looks good.
Please add to the Changes file before merging.
Thanks.

**Comment by vincentl** [comment]
Commit 0777011539024cb003109a78917139672e8644ab updates Changes.

**Pull request merged**
