### PR TITLE
Update get features to include description for GnuCash

### PR DESCRIPTION
**Pull request by vincentl**
@bpschuck - I was able to complete the changes quickly, so I went ahead and made this PR.

If you run

```bash
DEBUG=1 dzil run prove -lv t/fq-class-methods.t
```
you can see how the structure of the returned hash from `get_features()` changed.  I think it adds what we need for the discussion in Gnucash as well as provides opportunities for new fields in the future without disrupting the fields as presented in this PR.

### CODE REVIEW

**Comment by bpschuck** [comment]
I likely will not take a close look at this for at least 2 weeks. This week I'm just reviewing the last bunch of merged PRs and doing housekeeping in preparation for releasing v1.58 this coming Saturday. The week of the 14th I have a business trip and will have little time for F::Q and other personal endeavors.
But I have to comment about the descriptions. Surely John Ralls is looking for something other than "Fetch quotes from XXX", where XXX is usually the module name (and also the method name as well). Think about that. It is somewhat redundant/repetitive and offers nothing more than users can glean from the method name. Begs the question, "why bother?" if the description really isn't anything more than "Fetch quotes from <method name>[.com,.org,.uk,...]".

**Comment by vincentl** [comment]
> Begs the question, "why bother?" if the description really isn't anything more than "Fetch quotes from [.com,.org,.uk,...]".

I agree that for some modules it doesn't add information for the user, but for some like DWS.pm (which I just realized had an update to the description so I need to fix the return string) I think it adds some value.

For the actual features, my original proposal was shortsighted.  I was thinking of just API keys.  But there is already a new use (for INST_ID) and it is nice to have a way to provide some brief documentation with the feature name.

I'm not even sure how these "descriptions" will be presented in the GnuCash API yet, so if you feel like this change adds more work per module (in either writing or maintaining) than the potential benefit then I'm happy to bring up this point in the GnuCash discussion.

I did update the Hackers-Guide in the PR to document what module writers should do.  (Note, the function is still optional, but I went ahead and added it to all the modules based on what was in the POD documentation for the module).

**Comment by bpschuck** [comment]
"Some"?! It's almost **all** of them! Some, like SIX.pm, at least mention what exchange the quotes will come from. What info should be in the description is a discussion you need to have with John. Then perhaps please have something much closer to being ready for a merge. What I would have found helpful years back when I first started using F::Q to update stock prices is knowing what stock exchanges the methods can retrieve data for (as SIX.pm). Knowing that `alphavantage` can retrieve prices for US, UK, and other exchanges for example. It's a new module, but knowing `stooq` is primarily the Warsaw Poland stock exchange, but data from other European exchanges are available. Maybe all the descriptions should include links to the main site? But back to my earlier comment, this needs to be discussed with Mr. Ralls. 
 Question, have you made and tested the changes to GnuCash that will utilize this information? If what is needed is still being discussed and developed, IMNSHO there should not be a PR.

**Comment by bpschuck** [comment]
Waiting for @jralls to comment. But while reviewing the changes and what `sub features()` returns for `description` in a bunch of the modules, my feeling was that descriptions similar to `"Fetch quotes from stooq.com"` does not really add more insight into what data the module could be used to retrieve. Stooq.pm is not the only one where the description returned is not much more than the module name. Yes, some of them have helpful info being returned. But if we're going to add it to every module, my thought is to at least take the time and effort to try to supply a meaningful description for all the existing modules. This would minimize a bunch of subsequent F::Q PRs as the description is updated for those modules needing a better description.
An example would be Stooq.pm returning something more like: 

> Acquires quotes from stooq.com. Primarily Polish/Warsaw Exchange, but data from other exchanges is available. See "perldoc Finance::Quote::Stooq".

Or is that too long a description for what John would like to see? If would be helpful to know that users can get USD quotes for something like `AAPL.US` or London Exchange quotes for `AAPL.UK`.

Would be cool if the "See..." text can be clicked on to open a pop-up window with the man page displayed. :)

@vincentl - Please keep this PR up to date with recent merged PRs. Thanks.

**Comment by jralls** [comment]
Darn, I thought that I had commented on this last week. I must have closed the tab without clicking comment.

Anyway, what @vincentl needs for his GnuCash PR is a human-friendly short name for each source suitable for displaying in a listbox. Some of them are obvious as-is but would look nicer if capitalized or punctuated, e.g. Alphavantage and TIAA-CREF. Others are a bit obscure or easily confused, e.g. aex (Euronext Amsterdam) and asx (Australia Stock Exchange).

As for sources some modules expose more than one with aliases. HU.pm is a good example, it has two methods, `bse` and `bamoz` that are exposed as  6 sources: `hufund, bamosz, hustock, bse, bet, hu, hungary`. `hufund` and `bamoz` alias `bamoz`, `hustock`, `bse`, and `bet` alias `bse`, and `hu` and `hungary` call a wrapper method that calls both of them. It would be nice to condense those into `Hungarian Stock Exchange`, `Hungarian Mutual Funds`, and `Hungarian Security Quotes`, but if they all return the same `description` string then deduplication can happen in GnuCash.

I agree that it would be nice to also have a brief writeup on what each source is able to retrieve but I can't think of a good way to display that in the UI since Gtk removed the ability to put tooltips on list entries.

> Acquires quotes from stooq.com. Primarily Polish/Warsaw Exchange, but data from other exchanges is available. See "perldoc Finance::Quote::Stooq".

The pointer to `perldoc Finance::Quote::Stooq` isn't terribly helpful because the Stooq POD isn't terribly helpful. It just says that it pulls quotes from https://stooq.com. I guess what you want is in the note at the bottom of the latter saying "LSE, LSE Intl, Nasdaq, NYSE, NYSE MKT and WSE quotes are supplied by [Infront](https://www.infrontfinance.com/). Cryptocurrencies quotes are supplied by [CoinAPI](https://www.coinapi.io/). TFI and UFK quotes are supplied by [mojeFundusze.pl](https://mojefundusze.pl/)."

**Comment by bpschuck** [comment]
> I agree that it would be nice to also have a brief writeup on what each source is able to retrieve but I can't think of a good way to display that in the UI since Gtk removed the ability to put tooltips on list entries.

Well that's unfortunate. Especially for the modules you pointed out that have aliased methods.

> The pointer to perldoc Finance::Quote::Stooq isn't terribly helpful because the Stooq POD isn't terribly helpful. It just says that it pulls quotes from https://stooq.com/. I guess what you want is in the note at the bottom of the latter saying "LSE, LSE Intl, Nasdaq, NYSE, NYSE MKT and WSE quotes are supplied by [Infront](https://www.infrontfinance.com/). Cryptocurrencies quotes are supplied by [CoinAPI](https://www.coinapi.io/). TFI and UFK quotes are supplied by [mojeFundusze.pl](https://mojefundusze.pl/)."

My plan is to add more descriptive text to the PODs as they get updated for other issues/bugs/etc. Maybe not to the degree you indicate, but using Stooq as an example, noting that quotes for securities traded on other exchanges aside from the Warsaw exchange are available. This would include examples of symbols for US, UK, or other exchanges (AAPL.US, GBP.UK, ...). Noting where Stooq (and other modules' sources) gets its data may be a bit too detailed, but if it's easily determined, why not.

**Comment by vincentl** [comment]
@bpschuck and @jralls - I would like to get back to finishing this project. Based on the above discussion, I propose
- Roll back the changes that added a description string 
  - there isn't a great way to display in GnuCash as a a tooltip
  - it isn't clear what can be said in short description beyond X.pm pull from X
- Keep the changes to the json format in this PR
- Once this PR is accepted, I can return to the GnuCash PR and finish that up

**Comment by jralls** [comment]
@vincentl ISTM it would make more sense to work on them in parallel. We can install both PRs for testing and that allows tweaking both to get the result we want.

**Comment by bpschuck** [comment]
I agree with Mr. @jralls. I'm not sure why @vincentl can think of brief descriptions for each module. X.pm - "Data from xxx.net. Warsaw exchange securities and funds." 
Also, not sure why there is a need to have the proposed changes pushed to the main branch? Surely Vincent can create his own dev environment that utilizes his changes to F::Q along with his changes to GnuCash. A couple years back I played with my own version of GnuCash that treated Crytpo as normal currencies. This utilized my own changes to GnuCash source along with some F::Q modifications. Completely isolated from the GnuCash/F::Q I use everyday, and that was without utilizing a VM for segregation.

**Comment by vincentl** [comment]
@jralls - I should have written that I wanted to get agreement on this PR to work in parallel on the GnuCash PR (and not wait until this was merged to main).

@bpschuck - Did you mean to write "**can't** think of" in your first sentence.  I had the impression you didn't think adding the description strings wasn't worth the effort to write & maintain.  If I had that wrong, we can keep the description strings.  Then I just need to rebase this PR & edit some strings to make them a bit more informative.

**Comment by bpschuck** [comment]
Yes, I meant "cannot think of"

**Comment by vincentl** [comment]
To achieve the goals of 
- provide a concise "display name" for each FQ method
- provide an optional "feature" to convey requirements such as API_KEY
- and, keep it simple

I am working on updating this PR to eliminate the proposed `feature` subroutine as well has the `labels` subroutine and merge everything into `methods`.  An example probably conveys the idea best.  Using Alphavantage.pm, I'm thinking 

```perl
our $DISPLAY    = 'AlphaVantage';
our $FEATURES   = {'API_KEY' => 'registered user API key'};
our @LABELS     = qw/date isodate open high low close volume last net p_change/;
our $METHODHASH = {subroutine => \&alphavantage, 
                   display => $DISPLAY, 
                   labels => \@LABELS,
                   features => $FEATURES};

sub methods {
    return ( 
        alphavantage => $METHODHASH,
        canada       => $METHODHASH,
        usa          => $METHODHASH,
        nyse         => $METHODHASH,
        nasdaq       => $METHODHASH,
    );
}
```

This addresses a long-standing design issue that the `methods` and `labels` routines needed to be manually synchronized to return information for all method names.

The features key is optional, so most modules will have `subroutine`, `display`, and `labels`.  For many of the modules, display may simply be the module name, but for those with an acronym or with truly multiple methods in a single module, `display` will be exactly what GnuCash needs.

**Comment by bpschuck** [comment]
I don't care for this. In this example, if a GnuCash user was looking to see if the "nyse" method returned, what would that user see? As data could come from one or more modules.

**Comment by vincentl** [comment]
We are having a parallel conversation at [GnuCash PR](https://github.com/Gnucash/gnucash/pull/1626), but I'm trying to separate FQ decisions from GnuCash decisions as best as possible.

For FQ, my latest proposal keeps the existing FQ API the same but combines the internal implementation of methods and label into a single methods that also adds the additional information this PR originally intended to address.

> In this example, if a GnuCash user was looking to see if the "nyse" method returned, what would that user see?

This is ultimately a GnuCash decision, but I think there are two good options
1. filter methods and only present single source methods **and** add a GnuCash feature to specify failover
1. -or- for multi-source methods `get_features()` would return the list of methods for "nyse", each having a concise display name, so GnuCash could present the list of display names. 

For the second option, as far as I can tell, FQ never had a canonical order for multi-source methods. In fact, the order could potentially change from run to run because the list is built while iterating over hash keys, which is not deterministic. So either we would need to invent a way to fix an order or leave it unspecified.

At this point, I'm favoring option 1. If we select this option then I'm happy to update all the `method` functions to conform to the updated proposal and going forward it should not be a burden for new modules. And then in GnuCash, we will have the information needed to create a more user friendly interface.

**Comment by vincentl** [comment]
My latest push implements the newest proposal.  I'm going to work on the GnuCash PR using this design for now.

**Comment by bpschuck** [comment]
Another problem I see with merging this PR is that once done and pushed to CPAN as part of a release, any program in the wild (including GnuCash and KMyMoney) that may call and use the methods functions would likely malfunction since this PR changes what is being returned. I am a huge proponent of changes being backwards compatible.

**Comment by vincentl** [comment]
@bpschuck - the intent of this PR is to only change the API with respect to `get_features()`.  This function was introduced in May 2023, so it doesn't have the legacy of most of FQ's API. I can't guarantee no package has started using `get_features()`, but I bet the chance is low.

Internally, there are more changes to streamline how modules return labels and methods, but that is all internal to FQ.

I am about to push a rebase of this PR onto that HEAD of master if you want to review the diffs against master. To see the history of `get_features()` it was introduced in commit 6d7444785286c82efb2dead6281e653c5b1e878f.

**Comment by bpschuck** [comment]
@vincentl 

Your branch, while GitHub reports has no conflicts with the base branch, reinserts lines in at least two files changed in somewhat recent PRs.

BSEIndia.pm - current state lines 27-33

```
# VERSION

use vars qw($BSE_URL);
$BSE_URL = "https://www.bseindia.com";

sub methods { return ( 'india' => \&bseindia,
                       'bseindia' => \&bseindia ); }

```

Your update-get-features branch lines 27-51

```
# VERSION

use vars qw($BSE_URL);
$BSE_URL = "https://www.bseindia.com";

my $cachedir = $ENV{TMPDIR} // $ENV{TEMP} // '/tmp/';
my $BSE_ZIP = $cachedir.'bseindia.zip';
my $BSE_CSV = $cachedir.'bseindia.csv';
my $DISPLAY = 'BSE Exchange India';
my @labels = qw/close last high low open prevclose exchange name/;

sub methods { 
    return (
        india => {
            subroutine => \&bseindia,
            display => $DISPLAY,
            labels => \@labels
        },
        bseindia => {
            subroutine => \&bseindia,
            display => $DISPLAY,
            labels => \@labels
        },
    );
}
```

There is a similar issue in NSEIndia.pm.

This needs to be addressed.

Thank you.

**Comment by vincentl** [comment]
@bpschuck - sorry - I misunderstood a rebase conflict. I removed the unused code and ran the online tests for both modules before pushing the latest version of this PR.

**Comment by bpschuck** [comment]
I know it's a pain in the ass, but sometimes it is best to start with a fresh clone of the master repository and rewrite the desired changes (especially if they are not really complex). I've resorted to doing this myself at least once, and maybe twice. In the end it's actually cleaner and you end up with one or two clean commits instead a half dozen or more.

**Comment by bpschuck** [comment]
> @bpschuck - the intent of this PR is to only change the API with respect to `get_features()`. This function was introduced in May 2023, so it doesn't have the legacy of most of FQ's API. I can't guarantee no package has started using `get_features()`, but I bet the chance is low.

> Internally, there are more changes to streamline how modules return labels and methods, but that is all internal to FQ.

Well... sort of.

Your changes to all the modules removes the `labels` subroutine/method that each module contained. Does it break GnuCash, no. But there is no guarantee that it is not used by someone using F::Q outside of GnuCash.

A quick snippet to demonstrate.

```
#!/usr/bin/perl
# vi: set ts=2 sw=2 noai ic showmode showmatch: 

use strict;

use Module::Load;

use constant DEBUG => $ENV{DEBUG};
use if DEBUG, 'Smart::Comments', '###';

my $modpath = "Finance::Quote::YahooWeb";

load $modpath;

my %labelhash = $modpath->labels;
### LabelHash: %labelhash
```

With F::Q as it has been, the output (with DEBUG set of course) is:

```
### LabelHash: {
###              yahooweb => [
###                            'symbol',
###                            'name',
###                            'exchange',
###                            'currency',
###                            'isodate',
###                            'last',
###                            'open',
###                            'high',
###                            'low',
###                            'volume'
###                          ]
###            }
```

But change PERL5LIB to point to where I cloned your repository and changed to the `update-get-features` branch and one will get:

```
Can't locate object method "labels" via package "Finance::Quote::YahooWeb" at /home/bschuck/work/finance-quote/foo.pl line 23.
```

I've been involved in too many deployment rollbacks or rushed bug fixes after a deployment where a change "will not affect any of our processes|customers|etc" to ignore this. Yes, F::Q was initially created specifically for GnuCash. But over the years, it has found its way into people's personal projects and at least one other OpenSource finance application (KMyMoney and StockManiac to name 2). A simple fix would be to add the labels method back into the modules, even though that may seem redundant. But that would guarantee that if there exists a usage of some other tool/program utilizing the `labels` method returned by any of the modules, that tool or program does not break with this PR.

**Comment by vincentl** [comment]
@bpschuck - I added back `labels` in each module. it uses the labels value in `methods` so the two functions return consistent lists. Added `t/fq-check-labels.t` that ensures each module has `labels`.

**Comment by bpschuck** [comment]
@vincentl 
Executing further tests, I'm concerned that the hash returned for each modules' `methods` subroutine has also changed from what it always has been and is not backwards compatible. Aside from other programs in the wild that may be using `->methods`, do you guarantee that if this is PR is merged and part of a new release pushed to CPAN, it will **NOT** break users of current and older releases of GnuCash?

**Comment by bpschuck** [comment]
@vincentl - I also see that the `# VERSION` line your pull request is missing from MorningstarCH.pm. Not a recent change, the missing line was added to MorningstarCH.pm 2 years ago. I cannot with confidence, merge this PR.

Like I said a few replies ago, 

> I know it's a pain in the ass, but sometimes it is best to start with a fresh clone of the master repository and rewrite the desired changes (especially if they are not really complex). I've resorted to doing this myself at least once, and maybe twice. In the end it's actually cleaner and you end up with one or two clean commits instead a half dozen or more.

Surely, this will take much less time than it would take me to go over all 50+ `.pm` files with a fine tooth comb.

**Comment by vincentl** [comment]
@bpschuck - Because we don't know everything that is dependent on FQ, I can't guarantee there isn't something that will break because of this PR. I think we have different philosophies about the costs and benefits of prioritizing backward compatibility. I'm closing this PR for now.

**Comment by bpschuck** [comment]
Your decision. My 2 main concerns were backwards compatibility WRT GnuCash primarily, but not to completely ignore possible uses outside of GnuCash, **and** being careful not to break or undo previous valid changes. Especially when merging a PR affects move than 50 files. Seeing the error of the missing `# VERSION` line while executing `dzil test` unfortunately indicates that changes in the PR were not tested as thoroughly as they perhaps should have been.

**Pull request closed without merging**
