### PR TITLE
AlphaVantage: Use GLOBAL_QUOTE API

### PR DESCRIPTION
**Pull request by edolstra**
This is more efficient (it only returns the latest price) and more importantly, some symbols recently stopped working with the TIME_SERIES_DAILY API (e.g. `IWDA.AS`). E.g.
```
$ curl 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=IWDA.AS&apikey=...'
{
    "Error Message": "Invalid API call. Please retry or visit the documentation (https://www.alphavantage.co/documentation/) for TIME_SERIES_DAILY."
}
```
but
```
$ curl 'https://www.alphavantage.co/query?function=GLOBAL_QUOTE&symbol=IWDA.AS&apikey=...'
{
    "Global Quote": {
        "01. symbol": "IWDA.AS",
        "02. open": "51.5100",
        "03. high": "51.9200",
        "04. low": "51.5100",
        "05. price": "51.7600",
        "06. volume": "93222",
        "07. latest trading day": "2019-08-30",
        "08. previous close": "51.4350",
        "09. change": "0.3250",
        "10. change percent": "0.6319%"
    }
}
```

### CODE REVIEW

**Comment by goodvibes2** [comment]
Hi edolstra, I see you have removed
$json_data->{'Information'} 
Have you tested the new function no longer returns an Information message if too many quotes are requested in the specified time interval?

**Comment by bpschuck** [comment]
@goodvibes2 - It looks like @edolstra left out 'Information' as part of 'Meta Data' which is not returned in the global quote API. Still looks for 'Information' in the 'Error Message'. But I also see that close is being set to price. According to the README, in the standard labels close is the previous day's close as noted in issue 129. Make that fix (`$info{ $stock, 'close' }   = $quote->{'08. previous close'};`), and I can merge this PR and close issue 129. Thank you for the contribution.

From README.md:

    name         Company or Mutual Fund Name
    last         Last Price
    high         Highest trade today
    low          Lowest trade today
    date         Last Trade Date  (MM/DD/YY format)
    time         Last Trade Time
    net          Net Change
    p_change     Percent Change from previous day's close
    volume       Volume
    avg_vol      Average Daily Vol
    bid          Bid
    ask          Ask
    close        Previous Close
    open         Today's Open
    day_range    Day's Range
    year_range   52-Week Range
    eps          Earnings per Share
    pe           P/E Ratio
    div_date     Dividend Pay Date
    div          Dividend per Share
    div_yield    Dividend Yield
    cap          Market Capitalization
    ex_div       Ex-Dividend Date.
    nav          Net Asset Value
    yield        Yield (usually 30 day avg)
    exchange     The exchange the information was obtained from.
    success      Did the stock successfully return information? (true/false)
    errormsg     If success is false, this field may contain the reason why.
    method       The module (as could be passed to fetch) which found this information.
    type         The type of equity returned

**Comment by bpschuck** [comment]
Using the correct labels and value assignments, this pull request will address issue #129.
I have modified .travis.yml (supported perl versions for Ubuntu xenial now start at 5.22), Modules-README.yml, and tweaked AlphaVantage.pm.

**Comment by goodvibes2** [comment]
@bpschuck, this is @edolstra's PR, not mine, so I don't understand your request...
I would like a nice meaningful error msg if too many quotes are requested but it seems to me that this PR breaks that.

**Comment by goodvibes2** [comment]
@bpschuck, I see now you meant you were going to make the change. Thanks very much.

**Pull request merged**
